#!/usr/bin/env bash
# This script is displaying bad luck good luck Best School
n=0
while [ $n -lt 11 ]
do
    if [ $n -eq 4 ]
then
    echo "bad luck"
    elif [ $n -eq 8 ]
then
echo "good luck"
else 
echo "Best School"
fi
(( n=n+1 ))
done
