#!/usr/bin/env bash
# This script is displaying information about the shool file
v="school"
if [ -e "$v" ]
then
    echo"school file exist"
    if [ -s "$v" ]
    then
	echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    if [ -f "$v" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file dont not exit"
fi
