#!/usr/bin/env bash
# displays information about the School file
F="school"
if [ -e "$F" ]
then
    echo "school file exists"
    if [ ! -s "$F" ]
    then
	echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    if [ -f "$F" ]
    then
	echo "school is a regular file"
    else
	echo "school file is not empty"
    fi
fi
